version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:300"
    depends_on:
      - db
