# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e438e4cc857b9ca46e1ef0583aa73d6445dd2b9d4b37e8a8e0c7c2ba430128b593fa36a22b39750fc44a73d16f93b37a18fa07caf32a882f7ec3b6f5cde70cbb

test:
  secret_key_base: 4718626f7d5328e75bb63edd41215d0213c52a8352a94e3ea8a60bf48b279e8ceb87af2baaf625e763ae9fb090cfd0a8ad55e89f9e67bdf69bd4e46c26f34f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
